SchoolManagement/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebServiceAssignment/WebServiceStudentSite/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebServiceAssignment/WebServiceStudentSite/src/classes/StudentSiteController.cls
public class StudentSiteController {
    
    public List<Student__c> stdList{set ;get ;} 
    public Student__c student{set ;get ;}
    public String selectedValue{set ;get ;}
    public boolean showDetail{set ;get ;}
    public ApexPages.StandardController controller;
    
    public StudentSiteController(ApexPages.StandardController con) {
        showDetail = false;
        student = new Student__c();
    }
    
	// Method Providing Student list
    public List<SelectOption> getselectList() {
        List<SelectOption> selectList = new List<SelectOption>();
        stdList = [select Name from Student__c];
        for(Student__c std : stdList) {
            selectList.add(new SelectOption(std.Id,std.Name));
        }
        return selectList;
    }
    
	//Method Providing Student Information
    public PageReference getStudent() {
        try{
            showDetail = true;
            student = [select Id,Name,lastName__c,Class__c,DOB__c from Student__c where id =:selectedValue limit 1] ;
            return null ;
        }
        catch(Exception e){
            return new PageReference('/apex/errorfinder');
        }
    }
}