SchoolManagement/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebServiceAssignment/WebServiceStudentSite/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses_Assignment/src/classes/TestGetStudentsOfAClass.cls
@isTest
public class TestGetStudentsOfAClass {
     @isTest static void testgetStudentOfClassByClassIDMethod(){
         List<student__c> expected=[Select name From Student__c where class__r.id = 'a0J28000000WAvp'];
             
         List<student__c> actual=GetStudentsOfAClass.getStudentOfClassByClassID('a0J28000000WAvp');
        System.assertEquals(expected, actual);
       }
    
    @isTest static void testgetStudentOfClassMethod(){
         Map<Id, List<student__C>> expected = new Map<Id, List<student__C>>();
         for(class__c parent : [select id,(select id from students__r) From class__c]) {
           expected.put(parent.Id, parent.students__r);
         }
             
        Map<Id,List<student__c>> actual=GetStudentsOfAClass.getStudentOfClass();
        System.assertEquals(expected, actual);
       }
}