SchoolManagement/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebServiceAssignment/WebServiceStudentSite/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Apex_Assignment/src/classes/GetStudentsOfAClass.cls
public class GetStudentsOfAClass {
   public static List<student__c> getStudentOfClassByClassID(String id)
   {
       List<student__c> students=[select name from student__c where class__r.id=:id];
       return students;
   }
    
    public static Map<Id,List<student__c>> getStudentOfClass()
   {
       Map<Id,List<student__c>> info=new Map<Id,List<student__c>>();
       for(class__c element :  [select id,(select id from students__r) From class__c])
       {
           info.put(element.Id,element.students__r);
       }
       return info;
   }
}