SchoolManagement/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VFPages-Part 1/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <picklist>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

WebServiceAssignment/WebServiceStudentSite/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SOQL_Validation_Workflow_Assignment/src/classes/SOQL.cls
public class SOQL {
	List<student__c> students1=[Select Name,DOB__c,Sex__c from student__c where LastName__c LIKE 'S%'];
    List<student__c> students2=[Select Name from student__c where class__r.Name  LIKE 'x%'];
    List<student__c> students3=[Select Name,class__r.Name  from student__c];
    List<Sobject> students4=[SELECT Name, (SELECT Name FROM students__r) FROM class__c];
    List<Sobject> students5=[Select Name from student__c where class__r.ClassTeacher__r.Name LIKE 's%'];
    List<Sobject> students6=[Select Name from student__c where Calendar_Year(DOB__c)>2000];
    List<Sobject> students7=[Select Name from lead where LastModifiedDate = THIs_Month];
    List<Sobject> students8=[SELECT Id, Name,(SELECT Name FROM Students__r ) FROM Class__c WHERE id IN (SELECT Class__c FROM Student__c WHERE Name LIKE 'S%')];
    List<Sobject> students9=[Select Name from contact where Subjects__c INCLUDES ('Hindi;English')];
    List<Sobject> students10=[Select Name from contact where Subjects__c INCLUDES ('Hindi','English')];
	
    
}