Apex_Assignment/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <label>BillToContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Apex_Assignment/src/classes/UpdateOpportunity.cls
public class UpdateOpportunity {
    public static void UpdateManagerOfOpportunity(List<Opportunity> opportunityList){
        
        List<Opportunity> opList = [Select id,name,BillToContact__c,Manager__c From Opportunity Where id in :opportunityList AND BillToContact__C != null
                                   And manager__C = null];
        
        for (Opportunity oop: opList){
           System.debug(oop.Id);
           Contact con = [Select account.id from contact where id = :oop.BillToContact__c];
          oop.Manager__c = con.AccountId;
          update(oop);
   		 }
    }
}