VFPages-Part-2/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

VFPages-Part-2/src/objects/PurchaseOrder__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>PurchaseOrder</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VFPages-Part-2/src/objects/PurchaseOrderLineItems__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder__c</fullName>
        <label>PurchaseOrder</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrderLineItems</label>
    <nameField>
        <label>PurchaseOrderLineItems Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestClasses_Assignment/src/classes/OnlineShoppingControllerTest.cls
@isTest
private class OnlineShoppingControllerTest {
    static Product2 testProduct1;
    static Product2 testProduct2;
    static Product2 testProduct3;
    static PageReference pageRef;
    static List<Product2> testProducts = new List<Product2>();
    static PurchaseOrderLineItems__c testLineItem;
    static List<PurchaseOrderLineItems__c> testLineItems;
    static PurchaseOrder__c testOrder;
    @testSetup
    public static void setupMethod(){
        testProduct1 = new Product2(Name='ProductA',Price__c=2000);
        testProduct2 = new Product2(Name='ProductB',Price__c=3000);
        testProduct3 = new Product2(Name='ProductC',Price__c=5000);
        testProducts.add(testProduct1);
        testProducts.add(testProduct2);
        testProducts.add(testProduct3);
        insert testProducts;
    }
    @isTest
    static void testProducts_RetrieveAllProducts_Retrieved() {
        OnlineShoppingController testController = new OnlineShoppingController();
        System.assertEquals(3,testController.Products.size());
    }
    @isTest
    static void testControllerWhenCartNotBlank_CartItemList_NotNull() {
        Test.startTest();
        testProduct1 = [Select Name,Price__c from Product2 where Name='ProductA'];
        testLineItem = new PurchaseOrderLineItems__c(Name='ProductA',Product__c=testProduct1.Id,Quantity__c=1);
        insert testLineItem;
        OnlineShoppingController testController = new OnlineShoppingController();
        Test.stopTest();
        System.assertEquals(1,testController.productsInCart.size());
    }
    @isTest
    static void testControllerWhenCartBlank_CartItemList_Null() {
        OnlineShoppingController testController = new OnlineShoppingController();
        System.assertEquals(0,testController.productsInCart.size());
    }
    @isTest
    static void testAddToCartNewItem_ItemAddInCart_ItemAdded() {
        Test.startTest();
        OnlineShoppingController testController = new OnlineShoppingController();
        testProduct3 = [Select Name, Price__c from Product2 where Name='ProductC'];
        testController.selectedProductId = testProduct3.Id;
        testController.addToCart();
        Test.stopTest();
        System.assertEquals(1, testController.productsInCart.size());
    }
    @isTest
    static void testAddToCartExistedItem_ItemQuantityIncrement_Incremented() {
        Test.startTest();
        OnlineShoppingController testController = new OnlineShoppingController();
        testProduct3 = [Select Name, Price__c from Product2 where Name='ProductC'];
        testController.selectedProductId = testProduct3.Id;
        testController.addToCart();
        testController.selectedProductId = testProduct3.Id;
        testController.addToCart();
        PurchaseOrderLineItems__c cartItem = testController.productsInCart[0];
        Test.stopTest();
        System.assertEquals(2, cartItem.Quantity__c);
    }
    @isTest
    static void testRemoveFromCart_ItemRemoveFromCart_Removed() {
        Test.startTest();
        OnlineShoppingController testController = new OnlineShoppingController();
        testProduct2 = [Select Name, Price__c from Product2 where Name='ProductB'];
        testController.selectedProductId = testProduct2.Id;
        testController.addToCart();
        testProduct3 = [Select Name, Price__c from Product2 where Name='ProductC'];
        testController.selectedProductId = testProduct3.Id;
        testController.addToCart();
        testLineItem = [Select Name from PurchaseOrderLineItems__c where Name='ProductC'];
        testController.selectedProductId = testLineItem.Id;
        testController.removeFromCart();
        Test.stopTest();
        System.assertEquals(1, testController.productsInCart.size());
    }    
    @isTest
    static void testProceedToPay_OpenDeliveryInfoPopUp_PopUpOpened() {
        Test.startTest();
        OnlineShoppingController testController = new OnlineShoppingController();
        testProduct2 = [Select Name, Price__c from Product2 where Name='ProductA'];
        testController.selectedProductId = testProduct2.Id;
        testController.addToCart();
        testController.proceedToPay();
        Test.stopTest();
        System.assertEquals(true, testController.personalInfoDisplayPopUp);
    }
    @isTest
    static void testPay_PlaceOrder_Placed() {
        Test.startTest();
        OnlineShoppingController testController = new OnlineShoppingController();
        testProduct2 = [Select Name, Price__c from Product2 where Name='ProductA'];
        testController.selectedProductId = testProduct2.Id;
        testController.addToCart();
        testController.proceedToPay();
        testOrder = testController.order;
        testOrder.Name = 'Suman';
        testOrder.Address__c = 'Jaipur';
        testOrder.Phone__c = '0000000000';
        testController.order = testOrder;
        testController.pay();
        Test.stopTest();
        System.assertEquals(testController.order.Id,testController.productsInCart[0].PurchaseOrder__c);
    }
}